"""Added job Applications

Revision ID: eabec547e91a
Revises: f3595e74917d
Create Date: 2024-07-25 00:50:07.970329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabec547e91a'
down_revision = 'f3595e74917d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume', sa.String(), nullable=False),
    sa.Column('cover_letter', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='applicationstatusenum'), nullable=False),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
